apiVersion: v1
kind: LimitRange
metadata:
  name: pod-lr
spec:
  limits:
    - type: Container
      default:
        cpu: 1
        memory: 1Gi
      defaultRequest:
        cpu: 500m
        memory: 500Mi
      max:
        cpu: 1
        memory: 1Gi
      min:
        cpu: 400m
        memory: 200Mi
