apiVersion: v1
kind: Pod
metadata:
  name: pod-rr
spec:
  containers:
    - name: img-redis
      image: redis:alpine
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 1
          memory: "1Mi"
        limits:
          cpu: 2
          memory: "2Mi"
        
