apiVersion: v1
kind: Pod
metadata:
  name: antiaff-pod-2
spec:
  containers:
    - name: img1
      image: redis
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: zone
          labelSelector:
            matchExpressions:
              - key: app
                values:
                  - bar
                operator: In
                  
                
