apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-ds
spec:
  selector:
    matchLabels:
      app: frontend
  template:
      metadata:
        name: test-pod1
        labels:
          app: frontend
      spec:
        containers:
          - name: test-container1
            image: nginx

