apiVersion: v1 
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
    spec:
      containers:
        - name: redis123
          image: redis
  replicas: 2
