apiVersion: v1
kind: LimitRange
metdata:
  name: cpu-limit-range
spec:
  limits:
    default:
      cpu: 500m
    defaultRequests:
      cpu: 500m
    max:
      cpu: 1
    min:
      cpu: 100m
    type:
      Container
