apiVersion: v1
kind: Pod
metadata:
    name: node-pod1
    labels:
        app: fe
spec:
    containers:
        - name: img1
          image: redis
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                        - key: size
                          operator: In
                          values:
                            - large
                            - medium
