apiVersion: v1
kind: Pod
metadata:
  name: pod-selct1
spec:
  containers:
    - name: img1
      image: redis:alpine
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large
                    Medium
            
