apiVersion: apps/v1
kind: Deployment
metadata:
  name: topospread-deploy-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      name: aff-pod
      labels:
        app: foo
    spec:
      containers:
        - name: img1
          image: registry.k8s.io/pause:2.0
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
           matchLabels:
             app: foo
