apiVersion: v1
kind: Pod
metadata:
  name: topopod-1
  #labels:
    #app: foo
spec:
  containers:
    - name: img1
      image: redis
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: size
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: front
