apiVersion: v1
kind: Pod
metadata:
  name: aff-node2
  labels:
    app: frontend
spec:
  containers:
    - name: pod2
      image: redis:alpine
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchFields:
              - key: metadata.name
                operator: NotIn
                values:
                  - k8s-cl-m04
