apiVersion: v1
kind: Pod
metadata:
  name: aff-node1
  labels:
    app: frontend
spec:
  containers:
    - name: pod1
      image: redis:alpine
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchFields:
              - key: metadata.name
                operator: In
                values:
                  - k8s-cl-m03
