# Custom Resource Definiton helps us creating resorces like pod, deployment and replicaset etc and to create these resources we will need to have Custom controllers
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flighttickets.flights.com
spec:
  # scope key helps to bind the object to Namespace or Cluster scope 
  scope: Namespaced
  # group is the api-group that will bound the resources, Ex. apps, networking.k8s.io
  group: flights.com
  # names helps kubectl and Kube-api-server by providing the kubectl necessary names to create and display resorces names
  names: 
    kind: flightTicket 
    singular: flightticket 
    plural: flighttickets
    shortNames: 
      - ft 
  # Verison provides the api group with the version of the api that is currently in used if changes in the future
  versions:

    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer

