apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
    #labels:
    #security: S1
spec:
  affinity:
    # podAffinity:
    #   #requiredDuringSchedulingIgnoredDuringExecution:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #   - labelSelector:
    #       matchExpressions:
    #       - key: security
    #         operator: In
    #         values:
    #         - S1
    #     topologyKey: size
    # podAntiAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #   - weight: 100
    #     podAffinityTerm:
    #       labelSelector:
    #         matchExpressions:
    #         - key: security
    #           operator: In
    #           values:
    #           - S2
    #       topologyKey: topology.kubernetes.io/zone
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: security
              operator: In
              values:
              - S2
          topologyKey: zone
  containers:
  - name: img1
    image: registry.k8s.io/pause:2.0
