apiVersion: apps/v1
kind: Deployment
metadata:
  name: aff-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      name: aff-pod
      labels:
        app: foo
    spec:
      containers:
        - name: img1
          image: registry.k8s.io/pause:2.0
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: zone
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - foo
